### ISSUE TITLE
ValueError: Non-stationary starting error autoregressive parameters found with `enforce_stationarity` set to True.

### ISSUE THREAD

**Issue by hgilles06** [ChadFulton/tsa-notebooks#10]
Hi,

I am getting some errors when running the notebook you provided. Isn't any problem with the default initialization ?

Thanks!

**Comment by hgilles06** [comment]
Hi, 
Thanks for your answer. It is the notebook about Dynamic factors and coincident indices (dfm_coincident.ipynb). I got first this error when managing the data : 
ValueError: shape mismatch: value array of shape (234,1) could not be broadcast to indexing result of shape (234,)
When I tried to fix it, and ran the model, then I got : 
ValueError: Non-stationary starting error autoregressive parameters found with `enforce_stationarity` set to True.

And then I set the parameter `enforce_stationarity` to "False", but I got another error. 

Best regards,
 

    On Tuesday, October 23, 2018 3:27 AM, ChadFulton <notifications@github.com> wrote:
 

 Hey, thanks for the bug report.Which notebook are you running into troubles with?—

**Comment by ChadFulton** [comment]
Thanks - I went through the notebook and had to fix a couple of index issues (like the one you mentioned), but I never ran into a problem with that ValueError. Which cell of the notebook is the error being raised in?

**Comment by hgilles06** [comment]
Cool. It's working now. Big thanks! 

    On Tuesday, October 23, 2018 2:11 PM, ChadFulton <notifications@github.com> wrote:
 

 Thanks - I went through the notebook and had to fix a couple of index issues (like the one you mentioned), but I never ran into a problem with that ValueError. Which cell of the notebook is the error being raised in?—

**Comment by ChadFulton** [comment]
Great!
