### ISSUE TITLE
AttributeError: 'odict_keys' object has no attribute 'index'

### ISSUE THREAD

**Issue by ArlenChiu** [ChadFulton/tsa-notebooks#11]
Hi Dr.Fulton, 

I have been working on how to do simulation of RBC model in python and your notebook (**simple_rbc**.ipynb) is greatly helpful. But when I tried to run the codes in IPython, some errors came out. 

First one is, **AttributeError: 'odict_keys' object has no attribute 'index'** in  
**self.idx_cap_share = parameters.index('capital_share')**.
I changed that to **self.idx_cap_share = list(parameters).index('capital_share')**. 
And it's fixed. 

However, another error emerged: **IndexError: too many indices for array** in 
**structural_params = np.array(self.parameters.values())[self.idx_estimated]** , 
**start_params = self.start_params** 
and 
**calibrated_res = calibrated_mod.fit(method='nm', maxiter=1000, disp=0)**. 
I have no clue how to fix this one. 

Sorry if I don't make myself clear. I just start to learning python and plan to use it in my academic research. I googled a lot about this error but nothing works. It would be a huge help if you could help me with this problem. If there's any other information you may need, please let me know. 

Thanks,
Tengyu

**Comment by ChadFulton** [comment]
Thanks for the note! I think this should be fixed in a new update.
