### ISSUE TITLE
setar_model cannot find some ._ method

### ISSUE THREAD

**Issue by xinhangs** [ChadFulton/tsa-notebooks#15]
Dear Chad,

Thank you for implementing setar_model and tsa_setar_sunspots_full.ipynb. There are some modules and methods start with "_" show missing.
Line 260 of setar_model.py: `beta = self._fit()` shows cannot find "_fit()"
Line 12 of tsa\statespace\tools.py: `from . import _statespace` shows cannot find "_statespace"
Is there anything I missed? Thank you.

**Comment by ChadFulton** [comment]
Hi @xinhangs, thanks for reporting the issue.

The version of `setar_model.py` that is in my development branch at https://github.com/ChadFulton/statsmodels/tree/setar depends on a couple of changes that were made in that branch that are not currently in Statsmodels master repository or the released versions.  For that reason, you can't just copy `setar_model.py` and use it with, for example, a released version of Statsmodels.

**Comment by xinhangs** [comment]
Thank you for your explanation. I tried pip install git and .zip but have not installed successfully yet. I will try it later.
