### ISSUE TITLE
thanks! but qd md def?

### ISSUE THREAD

**Issue by vks2** [ChadFulton/tsa-notebooks#17]
Thank you for this notebook.
Could you share, pls 'fredmd_definitions.csv' and 'fredqd_definitions.csv'
Guess you've made it manually.

**Comment by ChadFulton** [comment]
Thanks for this note, I meant to include those files here, and I should be able to put them up soon.

**Comment by vks2** [comment]
Here you've got one of them

**Comment by vks2** [comment]
And the second, just in case
[fredqd_definitions.zip](https://github.com/ChadFulton/tsa-notebooks/files/5183843/fredqd_definitions.zip)

**Comment by vks2** [comment]
you did better, than tabula-py
still miss your files, you matched factors by description that actually do not match with my generated ver.

**Comment by ChadFulton** [comment]
Thanks for bringing that up, I haven't used tabula-py before. The formatting on the PDF tables is weird (I had to correct a lot of things by hand after I did a PDF-to-Excel translation), and it looks like it did a pretty good job.

I'll add these files to the repository soon, but here they are in the meantime.

[fred_mdqd_definitions.zip](https://github.com/ChadFulton/tsa-notebooks/files/5183921/fred_mdqd_definitions.zip)

**Comment by vks2** [comment]
lot of manual work too with tabula-py but its better than all the rest that i tested. 

thank you for files. and for the project! on my opinion it's more interesting than matlab code published by well-known researchers, and not too much of low-coding (it's in the lib, actually).

btw, have you tested how precise the model could be if we pick only some of variables or combining them, some best fit features, "golden" ones?
my best guess it to see model.fit on different sets of feats and pick one model from them, but even with ML algo it takes time, if we construct not 10 models, but 100-200 or more. 
anyway i'll try to run it on GPU (this week) to see if it will help.

Thanks again!

**Comment by ChadFulton** [comment]
> thank you for files. and for the project! on my opinion it's more interesting than matlab code published by well-known researchers, and not too much of low-coding (it's in the lib, actually).

Thanks! I'm glad it's useful.

I've added the files to the repository in 0bd5ef7, so I'll close this issue.
