### ISSUE TITLE
I am getting this error AttributeError: module 'statsmodels.tsa.api' has no attribute 'DynamicFactorMQ'

### ISSUE THREAD

**Issue by Mamakgooa** [ChadFulton/tsa-notebooks#19]

**Comment by Mamakgooa** [comment]
I tried upgrading pip and statsmodels and there is still no luck

**Comment by Mamakgooa** [comment]
I had to reinstall Python. 

How of ten does the data set get updated

**Comment by ChadFulton** [comment]
> How often does the data set get updated

If you mean the FRED-MD dataset that is used in the "Large dynamic factor models, forecasting, and nowcasting" notebook, then that dataset is updated once a month, and can be found at https://research.stlouisfed.org/econ/mccracken/fred-databases/

However, I am not currently updating the notebook to account for new FRED-MD datasets.
