### ISSUE TITLE
Details on calibration?

### ISSUE THREAD

**Issue by amacfie** [ChadFulton/tsa-notebooks#20]
For this notebook: https://github.com/ChadFulton/tsa-notebooks/blob/master/estimating_rbc.ipynb

Can you provide any details on how the values
```disutility_labor=3, depreciation_rate=0.025, capital_share=0.36```
were calculated?

**Comment by ChadFulton** [comment]
These are the values used in the Ruge-Murcia, 2007 ("Methods to Estimate Dynamic Stochastic General Equilibrium Models") Monte Carlo analysis.
