### ISSUE TITLE
Problem - Large dynamic factor models, forecasting, and nowcasting

### ISSUE THREAD

**Issue by scfhath** [ChadFulton/tsa-notebooks#24]
First of all, thank you very much for your extremely helpful notes and examples. 

I am having an issue with the DFM nowcasting model, specifically the line: 
for date in dta.keys():
    dta[date].dta_m = dta[date].dta_m.reindex(columns, axis=1)
I get this error: ValueError: cannot reindex from a duplicate axis

Omitting this line then also gives the same error when I try to construct the model:
model = sm.tsa.DynamicFactorMQ(
    endog_m, endog_quarterly=endog_q,
    factors=factors, factor_orders=factor_orders,
    factor_multiplicities=factor_multiplicities)

I wonder whether you can advise. Everything else until that point is fine. I constructed the description files as you did.

Thanks so much.

**Comment by scfhath** [comment]
Issue caused from the differences in the definition files. I found the original definition files in another question comment. Closing issue. Thank you!

**Comment by ChadFulton** [comment]
Glad to hear things are working now!
