### ISSUE TITLE
BUG/REF: FRED MD/QD links don't work

### ISSUE THREAD

**Issue by ChadFulton** [ChadFulton/tsa-notebooks#26]
It appears that FRED MD and FRED QD are no longer hosted on AWS, but instead directly on FRED's website (e.g. https://files.stlouisfed.org/files/htdocs/fred-md/monthly/current.csv).

**Comment by jfreeze3** [comment]
Thank you for sharing this work.  I appreciate your effort and step-by-step explanatory walk-through of the process.

Brett Freeze

**Comment by ChadFulton** [comment]
Thanks @jfreeze3, glad to hear it!

**Comment by jfreeze3** [comment]
How hard would it be to run an r-squared between the GDP forecasts using Feb, May, Aug, and Nov datasets against the actual quarterly GDP data, for the data through 1999 and separately for the data from 2000 forward?

**Comment by ChadFulton** [comment]
> How hard would it be to run an r-squared between the GDP forecasts using Feb, May, Aug, and Nov datasets against the actual quarterly GDP data, for the data through 1999 and separately for the data from 2000 forward? 

Computing an R^2 is not difficult, since it is just: R^2 = 1 - SSE_model / SSE_null_model. For linear regression, the null model is simply fitting a constant.

However, in time series models, fitting a constant is not necessarily the benchmark you want to be comparing against.  However, you can certainly compute the SSE of the GDP forecast using `DynamicFactorMQ` and compare that against some alternative model (for example, a random walk or some AR(p) model).

But unfortunately nothing is built-in to do that for you yet (there is a partially-completed pull request [here](https://github.com/statsmodels/statsmodels/pull/6620) to add some simple R^2 variants to Statsmodels).

**Comment by ChadFulton** [comment]
Closed by https://github.com/ChadFulton/tsa-notebooks/commit/371459df3f975947201d5f4029729b4cde7dab61
