### ISSUE TITLE
Construct the dynamic factor model - Coding Issue

### ISSUE THREAD

**Issue by ryanm789** [ChadFulton/tsa-notebooks#33]
Hi Chad,

Thank you very much for your model and walk through notes.  I am running into the following error whenever I attempt to run:

# Construct the dynamic factor model
model = sm.tsa.DynamicFactorMQ(
    endog_m, endog_quarterly=endog_q,
    factors=factors, factor_orders=factor_orders,
    factor_multiplicities=factor_multiplicities)

"If a `factors` dictionary is provided, then it must include entries for each observed variable. Missing variables are: {nan}."

This is despite having the factors dictionary established with each variable having a corresponding group as per the following image.

![image](https://user-images.githubusercontent.com/95641962/147131644-14be3f11-a091-4082-be2f-4b8cbbca4310.png)

Anything you might be able to share in solving this issue would be greatly appreciated.

Thank you,

Ryan

**Comment by Tvogel20** [comment]
Would be also interested how to fix this. Many thanks

**Comment by ChadFulton** [comment]
Fixed by https://github.com/ChadFulton/tsa-notebooks/commit/371459df3f975947201d5f4029729b4cde7dab61
