### ISSUE TITLE
Reproducing results 

### ISSUE THREAD

**Issue by msh855** [ChadFulton/tsa-notebooks#38]
Hi, 

Thank you for the examples. But I have hard time replicating your results using your notebook. I have no access to: 
```

 base_url = 'https://s3.amazonaws.com/files.fred.stlouisfed.org/fred-md'
    
    # - FRED-MD --------------------------------------------------------------
    # 1. Download data
    orig_m = (pd.read_csv(f'{base_url}/monthly/{vintage}.csv')
                .dropna(how='all'))
    
```

Is possible to make the dataset available ?

**Comment by celowiz** [comment]
You can make this change to the code:
`base_url = 'https://files.stlouisfed.org/files/htdocs/fred-md'`

**Comment by msh855** [comment]
Thanks. This is insufficient. The code downloads other data that is merged with this one. It seems however that this data has changed (in terms of source and format) making the reproduction of the results quite challenging.

**Comment by ChadFulton** [comment]
As of commit https://github.com/ChadFulton/tsa-notebooks/commit/371459df3f975947201d5f4029729b4cde7dab61, the notebook has been updated to pull from the new data location.

**Comment by msh855** [comment]
The code still fails. 

As mentioned in the earlier comment, there are two parts that need to be updated. The second part relates in reading the files for the description of the data (The links of the notebook do not work) 

This is the part that fails: 
```

# Definitions from the Appendix for FRED-MD variables
defn_m = pd.read_csv('data/fredmd_definitions.csv')
defn_m.index = defn_m.fred

# Definitions from the Appendix for FRED-QD variables
defn_q = pd.read_csv('data/fredqd_definitions.csv')
defn_q.index = defn_q.fred

# Example of the information in these files:
defn_m.head()
```

**Comment by ChadFulton** [comment]
It doesn't fail for me there. Did you download those files from the repository? https://github.com/ChadFulton/tsa-notebooks/tree/master/data

**Comment by msh855** [comment]
No, will do this now. Maybe good to mention this in the notebook. Thanks
