### ISSUE TITLE
The GDP forecast is not equal to the total impact

### ISSUE THREAD

**Issue by bigcodata** [ChadFulton/tsa-notebooks#39]
Hi Chad,
Thank you so much for your work on statsmodels and DynamicFactorMQ. I have one question. 2020-02 - 2020-06 forecast for real GDP growth in 2020Q2 are 2.68%, 2.52%, -8.23%,-37.17%, -22.33%,  respectively (In [32]). Total impact on 2020Q2 forecast from 2020-02 - 2020-06 are 0.16, -10.70, -29.30, 17.18. I found some difference between the total impact value and the change in GDP growth rate. For example, -22.33%-37.17% = 14.84% , not equal to 17.18. So what is the reason for the difference between the two?

Thank you so much.

**Comment by ChadFulton** [comment]
The impacts shown in that cell are computed from the "news", which is defined in the reference paper ("Now-casting and the real-time data flow", Banbura et al (2013)) as changes to the forecast that arise from new datapoints.

However, there can also be revisions to datapoints that had previously been published, and those revisions can also change the forecast. That is where the difference is coming from.

In https://github.com/statsmodels/statsmodels/pull/8028 I added computation of the impacts from specific forecast revisions to the output from the `news` method. However, that has very poor performance for large models like the DynamicFactorMQ example. This will be addressed soon (see https://github.com/statsmodels/statsmodels/issues/8920).

(Closing as answered but feel free to follow up if you have additional questions)
