### ISSUE TITLE
DFM: forecasting quarterly variables

### ISSUE THREAD

**Issue by JUANRUIZ87** [ChadFulton/tsa-notebooks#40]
Following the code described in Chad Fulton "Large dynamic factor models, forecasting and nowcasting", and using the method get_prediction for forecasting and nowcasting of quarterly variables (GDP), should I resample the forecast output (mean of the quarter)? Or this method already resamples the data (i.e. Mariano Murasawa) and the estimated GDP of the quarter is simply the value of the third month of each quarter?

**Comment by ChadFulton** [comment]
Yes you're correct: if you are calling the model as e.g. `mod = DynamicFactorMQ(data_monthly, endog_Q=data_quarterly, ...)` then it is using the Mariano & Murasawa approach, so the estimated GDP is the third month of the quarter.

I usually implement it like this:

```python
mod = DynamicFactorMQ(data_monthly, endog_Q=data_quarterly, ...)
res = mod.fit()

# Forecast for all variables, index is monthly
fcast = res.forecast('2023-12')

# For quarterly variables, get the quarterly forecast as the last month of the quarter
fcast_Q = fcast['GDP'].resample('Q').last()
```
