### ISSUE TITLE
'SimpleRBC' object has no attribute 'simulation_smoother'

### ISSUE THREAD

**Issue by haginile** [ChadFulton/tsa-notebooks#6]
Hi Chad,

I was trying to reproduce the SimpleRBC notebook and got the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-5e9b9ae9a7e9> in <module>()
     34 }
     35 model = SimpleRBC(rbc_data, calibrated=calibrated)
---> 36 sim_smoother = model.simulation_smoother()
     37 
     38 # Specify priors

AttributeError: 'SimpleRBC' object has no attribute 'simulation_smoother'
```

Is there a replacement function that I should be calling? Thanks!

**Comment by ChadFulton** [comment]
To use the simulation smoother, you need to install the development version of Statsmodels from Github. In addition, there will likely be a new release of Statsmodels including this feature in September or October.
